Check if `make` is available before calling it.

diff --git a/bin/eastoriented-library b/bin/eastoriented-library
--- a/bin/eastoriented-library
+++ b/bin/eastoriented-library
@@ -2,4 +2,9 @@
 
 set -e
 
-$(which make) -f vendor/eastoriented/library/Makefile "$@"
+if ! [ -x "$(command -v make)" ]; then
+  echo 'Error: `make` is not installed.' >&2
+  exit 1
+fi
+
+make -f vendor/eastoriented/library/Makefile "$@"
