Add missing requirements in README.

diff --git a/resources/bin/eastoriented-library b/resources/bin/eastoriented-library
--- a/resources/bin/eastoriented-library
+++ b/resources/bin/eastoriented-library
@@ -2,9 +2,19 @@
 
 set -e
 
+if ! [ -x "$(command -v docker)" ]; then
+  echo 'Error: `docker` is not installed.' >&2
+  exit 1
+fi
+
 if ! [ -x "$(command -v make)" ]; then
   echo 'Error: `make` is not installed.' >&2
-  exit 1
+  exit 2
+fi
+
+if ! [ -x "$(command -v git)" ]; then
+  echo 'Error: `git` is not installed.' >&2
+  exit 3
 fi
 
 make -f vendor/eastoriented/library/Makefile "$@"
